### ISSUE TITLE
Why don't u use TryParse?

### ISSUE THREAD

**Issue by AlexKap23** [mondifago/TicTacToe#2]
https://github.com/mondifago/TicTacToe/blob/60d3d9de419e4c361b4b965b734feb086b50f26f/TicTacToe/UIMethod.cs#L21-L45

How about using TryParse method to validate the input? This will enable your program to skip having so many catch blocks. 
https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-8.0

Using it will also make the code more readable and easier to understand.

**Comment by mondifago** [comment]
Done
