### ISSUE TITLE
Create constant for pipe

### ISSUE THREAD

**Issue by AlexKap23** [mondifago/TicTacToe#3]
https://github.com/mondifago/TicTacToe/blob/60d3d9de419e4c361b4b965b734feb086b50f26f/TicTacToe/UIMethod.cs#L104

Symbol | or pipe, can have it's own constant. After all this is just a hardcoded string. Create a constant and use that instead

**Comment by mondifago** [comment]
public const string VERTICAL_LINE = "|"; created for the pipe.
